### PR TITLE
Make the chart colour blind friendly

### PR DESCRIPTION
**Pull request by ghost**
The chart was red and green. That would be a bitch for anyone who was
colour blind. Now it consists of green ticks and red crosses.

### CODE REVIEW

**Comment by ghost** [comment]
I have brought this up to date with recent changes now.

**Comment by ghost** [comment]
Updated so that the yellow and green ticks are distinguishable from each other.

**Comment by helb** [comment]
Thanks. :+1: 
I drew some simple icons so it looks consistent across various systems/fonts…

**Comment by ghost** [comment]
No problem. I wasn't sure if the unicode icons I chose would render correctly across all browsers/font sets.

Date: Wed, 3 Jun 2015 03:25:37 -0700

**Pull request closed without merging**
