### PR TITLE
Clarify some launchpad details

### PR DESCRIPTION
**Pull request by CameronNemo**

### CODE REVIEW

**Comment by marekr** [comment]
I would say "many features not supported" is horrible wording.

You can push, pull, propose merges, see code, see summaries.  What else could there possibly be to git? 

Otherwise alpha quality/unfinished support is better.

**Comment by fitojb** [comment]
“no support or guidance available” is misleading at best, IMHO. Never joined their IRC channel?

**Comment by CameronNemo** [comment]
I am specifically talking about self hosting there. Do they really support that?

**Comment by CameronNemo** [comment]
Yeah they definitely do not support that. All their documentation is specific towards the main site, not self hosting. To self host you need to strip all the trademarked launchpad logos and what not -- this is not something you can easily do as a small project.

**Comment by helb** [comment]
Thanks, didn't know that. The first version of table was largely based on data from Wikipedia… Everytime i end up on Launchpad it's some sort of "where the fuck do i get some tarball or vcs link in this hellish interface" experience. :D

**Pull request merged**
